Repository treeverse/airflow-provider-lakeFS, pull requests merged in 2023-08, with the labels that each got.

#75 Bump version to 0.46.3
  setup.py
Labels: merge if approved

#70 feat: add branch delete operator
  lakefs_provider/example_dags/lakefs-dag.py
  lakefs_provider/hooks/lakefs_hook.py
  lakefs_provider/operators/delete_branch_operator.py
Labels: enhancement, contributor

#76 Add client ID to lakeFS client connections
  lakefs_provider/__init__.py
  lakefs_provider/hooks/lakefs_hook.py
  setup.py
Labels: enhancement

#78 Release 0.47.0
  lakefs_provider/__init__.py
Labels: merge if approved
