Repository treeverse/airflow-provider-lakeFS, pull requests merged in 2023-05, with the labels that each got.

#58 Refactor DAG run metadata and add it to merges
  .github/workflows/provider.yaml
  lakefs_provider/example_dags/lakefs-dag.py
  lakefs_provider/operators/commit_operator.py
  lakefs_provider/operators/merge_operator.py
  lakefs_provider/operators/with_metadata_operator.py
Labels: enhancement, team/ecosystem

#59 Add LakeFS commit links to commit and merge operators
  lakefs_provider/__init__.py
  lakefs_provider/hooks/lakefs_hook.py
  lakefs_provider/links/__init__.py
  lakefs_provider/links/lakefs_link.py
  lakefs_provider/operators/commit_operator.py
  lakefs_provider/operators/merge_operator.py
  setup.py
Labels: team/ecosystem

#61 Bump version to 0.46.1 to re-release with extra links feature
  CHANGELOG.md
  setup.py
Labels: team/ecosystem, merge if approved

#64 Add units missing units to structured metadata fields
  lakefs_provider/operators/with_metadata_operator.py
Labels: bug, team/ecosystem

#66 Update lakefs client to 0.101.0
  CHANGELOG.md
  requirements.txt
Labels: merge if approved
